In [1]:
#basic package
import json
import tqdm
import os
import numpy as np
import glob
import pandas as pd
import sys
import shutil
import time
import datetime as dt
import itertools
import time
import re
from collections import Counter
from collections import defaultdict
import operator
import math
import functools
import collections

#plot
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from UTILS import preprocessing_experiment2, general_cleaning, simple_cleaning_experiment2,verification_based_on_initial_record,\
OneTimeSeriesPlot, ZoneVariable, HenVariable, print_color, boxplot_distribution_entropy, heatmap_duration_perzone_perhen, \
time_series_henColumn_tsRow, cleaning_mouvement_records, TimeSeriesPlot_1row1day
import config_experiment2 as config

c:\users\camil\anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
c:\users\camil\anaconda3\lib\site-packages\scipy\sparse\sparsetools.py:21: DeprecationWarning: `scipy.sparse.sparsetools` is deprecated!
scipy.sparse.sparsetools is a private module for scipy.sparse, and should not be used.
  _deprecated()

we restrict the time series to one value per 60 seconds
we compute the complexity variables each 30 minutes
each variables includes the values of at least the last 120.00 minutes (i.e. are using 120.00 values)

# Define parameters

In [3]:
print('change the configuration file if not done yet!')
path_extracted_data = config.path_extracted_data
id_run = config.id_run
dico_matching = config.dico_matching
bining_sec = 60

change the configuration file if not done yet!

# Variables at Hen level

In [4]:
#for being more reproductible, we open the file that was saved from cleaning
df_ts = pd.read_csv(os.path.join(path_extracted_data, id_run+'_TimeSeries'+str(bining_sec)+'.csv'), sep=';', 
                    parse_dates=['New_Timestamp']) 
print(df_ts.shape)
print(min(df_ts['New_Timestamp']), max(df_ts['New_Timestamp']))
df_ts.head(3)

(146319, 109)
2019-11-05 09:35:00 2020-03-27 00:00:00

,New_Timestamp,hen_10bb,hen_10bs,hen_10gb,hen_10gg,hen_10gp,hen_10gs,hen_10pb,hen_10pp,hen_10ps,...,hen_5ps,hen_5sb,hen_5sg,hen_5sp,hen_5ss,hen_5sws,hen_5wb,hen_5wg,hen_5wp,hen_5ws
0,2019-11-05 09:35:00,5 Zone,2 Zone,3 Zone,2 Zone,5 Zone,2 Zone,2 Zone,5 Zone,5 Zone,...,5 Zone,5 Zone,2 Zone,5 Zone,2 Zone,5 Zone,3 Zone,4 Zone,2 Zone,3 Zone
1,2019-11-05 09:36:00,5 Zone,2 Zone,3 Zone,2 Zone,5 Zone,2 Zone,2 Zone,5 Zone,5 Zone,...,5 Zone,5 Zone,2 Zone,5 Zone,2 Zone,5 Zone,3 Zone,4 Zone,2 Zone,3 Zone
2,2019-11-05 09:37:00,5 Zone,2 Zone,3 Zone,1 Zone,5 Zone,2 Zone,2 Zone,5 Zone,5 Zone,...,5 Zone,5 Zone,2 Zone,5 Zone,2 Zone,5 Zone,3 Zone,4 Zone,2 Zone,3 Zone

#small verification
for d in df_ts['day'].unique():
    plt.plot(df_ts[df_ts['day']==d]['Timestamp'].tolist(), 
             df_ts[df_ts['day']==d]['is_day'].tolist())
    plt.title(d)
    plt.show()

#with:
dico_night_hour = {dt.datetime(2019,11,15,0,0,0):{'start_day_h':3,'start_day_m':5,'end_day_h':17,'end_day_m':25},
                   dt.datetime(2019,12,15,0,0,0):{'start_day_h':3,'start_day_m':0,'end_day_h':16,'end_day_m':15},
                   dt.datetime(2020,11,18,0,0,0):{'start_day_h':3,'start_day_m':15,'end_day_h':16,'end_day_m':15}}

#df_ts[df_ts['is_day']]
df_ts[(df_ts['Timestamp']<=dt.datetime(2019,11,15,17,26,15)) & \
     (df_ts['Timestamp']>dt.datetime(2019,11,15,3,4,40))][['Timestamp', 'is_day']]

### level=day

In [5]:
ts_name = 'time_serie_day'

In [6]:
#open time series per session and compute the variables for each session (car time series make sence at session level), et en 
#plus des variables tel que running entropy over the whole session ateach last timestamp of each level make sence only at 
#session level
df_daily = HenVariable(df_ts, config, ts_name, name_='', timestamp_name='New_Timestamp',
                       compute_chi2_distance=False, save=True, time4entropy=False)
print(df_daily.shape)
df_daily.head(3)

----------------- total duration per Zone....
The number of hours per "level" period is of:

Zone,verification_daily_total_nbr_hour,level,HenID
0,7.416667,"[2019-11-05 00:00:00, 2019-11-05 00:00:00, 201...","[hen_10bb, hen_10bs, hen_10gb, hen_10gg, hen_1..."
1,15.000000,"[2019-11-06 00:00:00, 2019-11-07 00:00:00, 201...","[hen_10bb, hen_10bb, hen_10bb, hen_10bb, hen_1..."

----------------- first time stamp in each zone per day....
----------------- number of Zone (excluding nan)....
----------------- compute some variables based on a list of zones over a day....

C:\Users\camil\Desktop\animals_code\PhD\UTILS.py:2397: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version
  df_ = df[~df['Zone'].isnull()].groupby(['HenID','level'])['Zone'].agg(function2apply).reset_index()

several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
several max-duration-zone
Total running time: 1.62 mn
(11016, 34)

,HenID,level,duration_1 Zone,duration_2 Zone,duration_3 Zone,duration_4 Zone,duration_5 Zone,verification_daily_total_duration,dur_values,dur_values_normalized,...,dico_zone_sortedduration,Total_number_transition,distribution_entropy,SampEnt_order2,nbr_bouts_5 Zone,nbr_bouts_2 Zone,nbr_bouts_3 Zone,nbr_bouts_4 Zone,nbr_bouts_1 Zone,Max_duration_zone_4
0,hen_10bb,2019-11-05,2700.0,10380.0,2160.0,300.0,11160.0,26700.0,"[2700.0, 10380.0, 2160.0, 300.0, 11160.0]","[0.10112359550561797, 0.3887640449438202, 0.08...",...,"{'4 Zone': [60, 60, 60, 60, 60], '2 Zone': [60...",60,1.217485,0.186540,11,23,15,5,7,0
1,hen_10bb,2019-11-06,3420.0,17100.0,4200.0,1740.0,27540.0,54000.0,"[3420.0, 17100.0, 4200.0, 1740.0, 27540.0]","[0.06333333333333334, 0.31666666666666665, 0.0...",...,"{'5 Zone': [60, 60, 240, 360, 480, 600, 600, 7...",94,1.191624,0.101369,15,37,27,5,11,0
2,hen_10bb,2019-11-07,5520.0,10140.0,4080.0,2100.0,32160.0,54000.0,"[5520.0, 10140.0, 4080.0, 2100.0, 32160.0]","[0.10222222222222223, 0.18777777777777777, 0.0...",...,"{'5 Zone': [60, 420, 420, 480, 540, 540, 540, ...",90,1.177265,0.074612,13,34,19,7,18,0