In [1]:
library(ctsem)
library(dplyr)
library(plyr)

Warning message:
"le package 'ctsem' a été compilé avec la version R 4.1.3"
Le chargement a nécessité le package : Rcpp

Warning message:
"le package 'Rcpp' a été compilé avec la version R 4.1.2"
ctsem also changes in time, for manual run ctDocs(), for blog see https://cdriver.netlify.app/, for citation info run citation('ctsem'), for original OpenMx functionality install.packages('ctsemOMX'), and for discussion https://github.com/cdriveraus/ctsem/discussions

Warning message in doTryCatch(return(expr), name, parentenv, handler):
"The following important packages for ctsem are out of date: rstan"
Warning message:
"le package 'dplyr' a été compilé avec la version R 4.1.2"

Attachement du package : 'dplyr'


Les objets suivants sont masqués depuis 'package:stats':

    filter, lag


Les objets suivants sont masqués depuis 'package:base':

    intersect, setdiff, setequal, union


Warning message:
"le package 'plyr' a été compilé avec la version R 4.1.2"
------------------------------------------------------------------------------

You have loaded plyr after dplyr - this is likely to cause problems.
If you need functions from both plyr and dplyr, please load plyr first, then dplyr:
library(plyr); library(dplyr)

------------------------------------------------------------------------------


Attachement du package : 'plyr'


Les objets suivants sont masqués depuis 'package:dplyr':

    arrange, count, desc, failwith, id, mutate, rename, summarise,
    summarize

In [3]:
setwd("G:/VPHI/Welfare/2- Research Projects/Camille Montalcini/Origins.GS/DataOutput/TrackingSystem/EXP2_")

# Download data

In [4]:
path_save = file.path('LongformatModels')
dir.create(path_save)
df = read.csv('df_longformatALL.csv', header = TRUE, sep = ",")
df$HenID = as.factor(df$HenID)   
df$ExperimentID = as.factor(df$ExperimentID)   
#tme is for now week of age
summary(df)
print(dim(df))
head(df)
#describe(df)

Warning message in dir.create(path_save):
"'LongformatModels' existe déjà"

     HAID                    HenID            id         MonthInstudy
 Length:2228        EXP3_hen_101:  12   Min.   :  1.0   Min.   :0.000
 Class :character   EXP3_hen_103:  12   1st Qu.:113.8   1st Qu.:0.820
 Mode  :character   EXP3_hen_104:  12   Median :220.0   Median :3.120
                    EXP3_hen_105:  12   Mean   :211.0   Mean   :3.511
                    EXP3_hen_106:  12   3rd Qu.:320.2   3rd Qu.:5.420
                    EXP3_hen_109:  12   Max.   :372.0   Max.   :9.500
                    (Other)     :2156
     DOAHA           IsOFH        ExperimentID  Is_relocated      Is_exp1
 Min.   :148.0   Min.   :0.0000   Exp1:798     Min.   :0.000   Min.   :0.0000
 1st Qu.:173.0   1st Qu.:0.0000   Exp2:796     1st Qu.:0.000   1st Qu.:0.0000
 Median :243.0   Median :0.0000   Exp3:634     Median :0.000   Median :0.0000
 Mean   :254.8   Mean   :0.1854                Mean   :0.175   Mean   :0.3582
 3rd Qu.:313.0   3rd Qu.:0.0000                3rd Qu.:0.000   3rd Qu.:1.0000
 Max.   :437.0   Max.   :1.0000                Max.   :1.000   Max.   :1.0000

    Is_exp2          Is_exp3        early_death        time2event
 Min.   :0.0000   Min.   :0.0000   Min.   :0.00000   Min.   :1.500
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:3.500
 Median :0.0000   Median :0.0000   Median :0.00000   Median :3.833
 Mean   :0.3573   Mean   :0.2846   Mean   :0.01391   Mean   :3.732
 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:0.00000   3rd Qu.:4.000
 Max.   :1.0000   Max.   :1.0000   Max.   :1.00000   Max.   :7.000

   meanDOAmvt        PropZ5         VTDperhour      zonecrossed2transition
 Min.   :144.5   Min.   :0.0000   Min.   : 0.0417   Min.   :1.000
 1st Qu.:211.2   1st Qu.:0.0601   1st Qu.: 2.6667   1st Qu.:1.012
 Median :241.5   Median :0.2077   Median : 3.7812   Median :1.030
 Mean   :271.2   Mean   :0.2858   Mean   : 3.8424   Mean   :1.062
 3rd Qu.:321.5   3rd Qu.:0.4608   3rd Qu.: 4.8776   3rd Qu.:1.081
 Max.   :433.5   Max.   :0.9699   Max.   :15.2292   Max.   :1.670
 NA's   :353     NA's   :353      NA's   :353       NA's   :987
   unevenness        severity           gap             weight
 Min.   :0.2043   Min.   :  0.00   Min.   :0.0000   Min.   :1228
 1st Qu.:0.5510   1st Qu.:  1.00   1st Qu.:0.0000   1st Qu.:1701
 Median :0.7095   Median : 16.00   Median :0.0000   Median :1790
 Mean   :0.8275   Mean   : 23.61   Mean   :0.2448   Mean   :1797
 3rd Qu.:1.0451   3rd Qu.: 38.00   3rd Qu.:0.0000   3rd Qu.:1886
 Max.   :1.9913   Max.   :100.00   Max.   :1.0000   Max.   :2331
 NA's   :353      NA's   :353      NA's   :353      NA's   :964
 test_weeksinbarn test_MonthInstudyround
 Min.   : 0.00    Min.   :0.000
 1st Qu.: 4.00    1st Qu.:0.820
 Median :13.00    Median :3.120
 Mean   :15.06    Mean   :3.511
 3rd Qu.:23.00    3rd Qu.:5.420
 Max.   :41.00    Max.   :9.500

[1] 2228   23

  HAID    HenID       id MonthInstudy DOAHA IsOFH ExperimentID Is_relocated
1 created EXP2_hen_1  1  0.00         148   0     Exp2         1
2 HA1     EXP2_hen_1  1  0.85         174   0     Exp2         1
3 HA2     EXP2_hen_1  1  3.16         244   0     Exp2         1
4 HA3     EXP2_hen_1  1  5.23         307   0     Exp2         1
5 HA4     EXP2_hen_1  1  7.99         391   0     Exp2         1
6 created EXP2_hen_10 2  0.00         148   0     Exp2         1
  Is_exp1 Is_exp2 ... meanDOAmvt PropZ5    VTDperhour zonecrossed2transition
1 0       1       ...  NA               NA       NA   NA
2 0       1       ... 170        0.1429359 3.680272   NA
3 0       1       ... 240        0.1195238 5.030612   NA
4 0       1       ... 303        0.1299773 5.112245   NA
5 0       1       ... 387        0.1178005 3.336735   NA
6 0       1       ...  NA               NA       NA   NA
  unevenness severity gap weight test_weeksinbarn test_MonthInstudyround
1        NA  NA       NA      NA  0               0.00
2 0.4956481   0        0  1691.7  4               0.85
3 0.4865883   0        0  1722.2 14               3.16
4 0.3923037   1        0  1655.2 22               5.23
5 0.2613006  18        0  1663.7 34               7.99
6        NA  NA       NA      NA  0               0.00

In [5]:
unique(df$HAID)

 [1] "created" "HA1"     "HA2"     "HA3"     "HA4"     "HA5"     "HA1A"
 [8] "HA2A"    "HA3A"    "HA4A"    "HA5A"    "HA6A"    "HA7A"    "HA8A"
[15] "HA9A"    "HA10A"   "HA11A"   "HA1B"    "HA2B"    "HA3B"    "HA4B"
[22] "HA5B"    "HA6B"    "HA7B"    "HA8B"    "HA9B"    "HA11B"   "HA10B"

In [6]:
colnames(df)

 [1] "HAID"                   "HenID"                  "id"
 [4] "MonthInstudy"           "DOAHA"                  "IsOFH"
 [7] "ExperimentID"           "Is_relocated"           "Is_exp1"
[10] "Is_exp2"                "Is_exp3"                "early_death"
[13] "time2event"             "meanDOAmvt"             "PropZ5"
[16] "VTDperhour"             "zonecrossed2transition" "unevenness"
[19] "severity"               "gap"                    "weight"
[22] "test_weeksinbarn"       "test_MonthInstudyround"

In [7]:
#TODO on final model, only relevant when optimize=FALSE, 
iter_ = 2000 
chains_ = 2 
bool_optimize = TRUE #documentation FALSE: "which also mean intoverpop will be set to FALSE automatically and therefore we integrates over 
#full sampling rather than population distribution of parameters"
#number of cpu cores to use to speed up
cores_ = 5 
folds_ = 3

# Hierarchical Bayesian continuous time dynamic model - MVT & KBF

In [8]:
#initialise what we want
variable = 'PropZ5' #VTDperhour PropZ5 zonecrossed2transition unevenness
rs=0

In [9]:
#head(df[,c('ExperimentID','IsOFH', 'Is_relocated','Is_exp1','Is_exp2','Is_exp3')],2)

In [10]:
############ 
name = paste0(variable, '_severity_trend_v2rs', rs, '_')
print(name)
#data_mvtha = subset(df,df$HAID!='created')
#data_mvtha = data_mvtha %>% select (id, MonthInstudy, severity, VTDperhour)
data_mvtha = df[,c('id', 'MonthInstudy', 'severity', variable,'IsOFH','Is_exp2','Is_exp3','weight')]
#data_mvtha = plyr::rename(data_mvtha, c('MonthInstudy'='time',"severity"="Y1", "VTDperhour"="Y2"))
#data_mvtha$Y1 = sqrt(data_mvtha$Y1)

#create directory
path_save_ = file.path(path_save,name)
dir.create(path_save_)
#convert into double (integer leads to warning as Y1 and Y2 are double)
#without centered TI: we get a warning: "Uncentered TI predictors noted -- interpretability may be hindered and default priors 
#may not be appropriate"
#centering and scaling variables in the model
li_sc = c('severity',variable)
data_mvtha[,li_sc] = scale(data_mvtha[,li_sc]) 
#warning if we have double and integer, and as Y1 and Y2 are double, let set them all
data_mvtha[li_sc] = sapply(data_mvtha[li_sc],as.double)
data_mvtha[c('IsOFH','Is_exp2','Is_exp3')] = sapply(data_mvtha[c('IsOFH','Is_exp2','Is_exp3')],as.double)

#pearson correlation
df_ = na.omit(data_mvtha[,c('MonthInstudy','severity', variable)])
dim(df_)
round(cor(df_[,c('MonthInstudy','severity', variable)], method = c("pearson")), 2)
round(cor(df_[,c('MonthInstudy','severity', variable)], method = c("spearman")), 2)
#show info
dim(data_mvtha)
head(data_mvtha,2)
summary(data_mvtha)
str(data_mvtha)

[1] "PropZ5_severity_trend_rs0_"

[1] 1875    3

             MonthInstudy severity PropZ5
MonthInstudy 1.00         0.51     0.08
severity     0.51         1.00     0.26
PropZ5       0.08         0.26     1.00

             MonthInstudy severity PropZ5
MonthInstudy 1.00         0.62     0.10
severity     0.62         1.00     0.19
PropZ5       0.10         0.19     1.00

[1] 2228    8

  id MonthInstudy severity  PropZ5    IsOFH Is_exp2 Is_exp3 weight
1 1  0.00                NA        NA 0     1       0           NA
2 1  0.85         -0.931354 -0.545743 0     1       0       1691.7

       id         MonthInstudy      severity           PropZ5
 Min.   :  1.0   Min.   :0.000   Min.   :-0.9314   Min.   :-1.0918
 1st Qu.:113.8   1st Qu.:0.820   1st Qu.:-0.8919   1st Qu.:-0.8621
 Median :220.0   Median :3.120   Median :-0.3003   Median :-0.2983
 Mean   :211.0   Mean   :3.511   Mean   : 0.0000   Mean   : 0.0000
 3rd Qu.:320.2   3rd Qu.:5.420   3rd Qu.: 0.5674   3rd Qu.: 0.6686
 Max.   :372.0   Max.   :9.500   Max.   : 3.0128   Max.   : 2.6138
                                 NA's   :353       NA's   :353
     IsOFH           Is_exp2          Is_exp3           weight
 Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :1228
 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:1701
 Median :0.0000   Median :0.0000   Median :0.0000   Median :1790
 Mean   :0.1854   Mean   :0.3573   Mean   :0.2846   Mean   :1797
 3rd Qu.:0.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1886
 Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :2331
                                                    NA's   :964

'data.frame':	2228 obs. of  8 variables:
 $ id          : int  1 1 1 1 1 2 2 2 2 2 ...
 $ MonthInstudy: num  0 0.85 3.16 5.23 7.99 0 0.85 3.16 5.23 7.99 ...
 $ severity    : num  NA -0.931 -0.931 -0.892 -0.221 ...
 $ PropZ5      : num  NA -0.546 -0.635 -0.595 -0.642 ...
 $ IsOFH       : num  0 0 0 0 0 0 0 0 0 0 ...
 $ Is_exp2     : num  1 1 1 1 1 1 1 1 1 1 ...
 $ Is_exp3     : num  0 0 0 0 0 0 0 0 0 0 ...
 $ weight      : num  NA 1692 1722 1655 1664 ...

In [11]:
Mdiffu = matrix(c(0,0,0,0,0,0,
              0,0,0,0,0,0,
              0,0,0,0,0,0,
              0,0,0,0,0,0,
              0,0,0,0,'diffu_dynKBF','diffu_dynMVT_dynKBF',
              0,0,0,0,0,'diffu_dynMVT'), ncol = 6)
Mdiffu

#"initial covariance matrices are fixed to zero in many elements such that these new dynamics processes do not interact or 
#co-vary with the other processes in the system"
Mt0var = matrix(c('T0var_KBF','T0var_MVT_KBF','T0var_cintKBF_KBF','T0var_cintMVT_KBF',0,0,
                  0,'T0var_MVT','T0var_cintKBF_MVT','T0var_cintMVT_MVT',0,0,
                  0,0,'T0var_cintKBF','T0var_cintMVT_cintKBF',0,0,
                  0,0,0,'T0var_cintMVT',0,0,
                  0,0,0,0,0,0,
                  0,0,0,0,0,0), ncol=6)
#TODO: no initial var in the dynamics process as it set to 0 always... correct?
Mt0var

#The initial state and continuous intercept for each dynamical process is set to zero, to ensure that the processes capture 
#only the fluctuations and not the general trends
Mt0means = matrix(c('T0m_KBF','T0m_MVT','T0m_cintKBF','T0m_cintMVT',0,0),ncol=1)
Mt0means
MCINT = matrix(c(0,0,0,0,0,0),ncol=1)

#"The auto-effect of the dynamics processes is estimated, setting the speed of the fluctuations"
Mdrift = matrix(c('drift_KBF',0,0,0,0,0,
                    0,'drift_MVT',0,0,0,0,
                    1,0,0,0,0,0,
                    0,1,0,0,0,0,
                    0,0,0,0,'drift_dynKBF','drift_dynMVT_dynKBF',
                    0,0,0,0,'drift_dynKBF_dynMVT','drift_dynMVT'), ncol = 6)
Mdrift

#initialize the model with two latent each with one manifest variable
#LAMBDA: n.manifest*n.latent loading matrix relating latent to manifest variables, with latent process 1:n.latent along the 
#columns, and manifest variables 1:n.manifest in the rows.
#DIFFUSION: lower triangular n.latent*n.latent cholesky matrix of diffusion process variance and covariance (latent error / 
#dynamic innovation). "auto" freely estimates all parameters.
#stanct’ for continuous time or ’standt’ for discrete time
model_fit = ctModel(type='stanct', n.manifest=2, n.latent=6, id="id", time="MonthInstudy",
                    manifestNames=c('severity',variable), latentNames=c('KBF','MVT','cintKBF','cintMVT','dynKBF','dynMVT'), 
                    T0MEANS=Mt0means, #initial state of dynamical process set to 0
                    T0VAR=Mt0var,
                    CINT = MCINT,
                    MANIFESTMEANS=matrix(c(0,0),ncol=1),
                    n.TIpred = 3, TIpredNames=c('Is_exp2','Is_exp3','IsOFH'),
                    LAMBDA=matrix(c(1,0, 
                                    0,1,
                                    0,0,
                                    0,0,
                                    1,0,
                                    0,1), ncol=6),  
                    DRIFT=Mdrift,
                    tipredDefault=FALSE,
                    DIFFUSION=Mdiffu) 

#we let ind. var in trend
model_fit$pars$indvarying[model_fit$pars$matrix %in% c('T0MEANS','CINT')] = TRUE
#https://discourse.mc-stan.org/t/r-package-ctsem-hierarchical-continuous-time-dynamic-models/117/14
#as we want some parameter in the system to vary by subject, we set very tight priors, as some individuals have only 3 timetamps
#model_fit$pars$sdscale[model_fit$pars$matrix %in% c('DRIFT')] = 0.05 #only for more complex like drit and manifestvar
model_fit$pars

     [,1] [,2] [,3] [,4] [,5]                [,6]
[1,] 0    0    0    0    0                   0
[2,] 0    0    0    0    0                   0
[3,] 0    0    0    0    0                   0
[4,] 0    0    0    0    0                   0
[5,] 0    0    0    0    diffu_dynKBF        0
[6,] 0    0    0    0    diffu_dynMVT_dynKBF diffu_dynMVT

     [,1]              [,2]              [,3]                  [,4]
[1,] T0var_KBF         0                 0                     0
[2,] T0var_MVT_KBF     T0var_MVT         0                     0
[3,] T0var_cintKBF_KBF T0var_cintKBF_MVT T0var_cintKBF         0
[4,] T0var_cintMVT_KBF T0var_cintMVT_MVT T0var_cintMVT_cintKBF T0var_cintMVT
[5,] 0                 0                 0                     0
[6,] 0                 0                 0                     0
     [,5] [,6]
[1,] 0    0
[2,] 0    0
[3,] 0    0
[4,] 0    0
[5,] 0    0
[6,] 0    0

     [,1]
[1,] T0m_KBF
[2,] T0m_MVT
[3,] T0m_cintKBF
[4,] T0m_cintMVT
[5,] 0
[6,] 0

     [,1]      [,2]      [,3] [,4] [,5]                [,6]
[1,] drift_KBF 0         1    0    0                   0
[2,] 0         drift_MVT 0    1    0                   0
[3,] 0         0         0    0    0                   0
[4,] 0         0         0    0    0                   0
[5,] 0         0         0    0    drift_dynKBF        drift_dynKBF_dynMVT
[6,] 0         0         0    0    drift_dynMVT_dynKBF drift_dynMVT

Warning message in ctStanModel(completemodel, type = type, tipredDefault = tipredDefault):
"TI predictors included but no effects specified!"

    matrix  row col param                 value
1   T0MEANS 1   1   T0m_KBF               NA
2   T0MEANS 2   1   T0m_MVT               NA
3   T0MEANS 3   1   T0m_cintKBF           NA
4   T0MEANS 4   1   T0m_cintMVT           NA
5   T0MEANS 5   1   NA                     0
6   T0MEANS 6   1   NA                     0
7   LAMBDA  1   1   NA                     1
8   LAMBDA  1   2   NA                     0
9   LAMBDA  1   3   NA                     0
10  LAMBDA  1   4   NA                     0
11  LAMBDA  1   5   NA                     1
12  LAMBDA  1   6   NA                     0
13  LAMBDA  2   1   NA                     0
14  LAMBDA  2   2   NA                     1
15  LAMBDA  2   3   NA                     0
16  LAMBDA  2   4   NA                     0
17  LAMBDA  2   5   NA                     0
18  LAMBDA  2   6   NA                     1
19  DRIFT   1   1   drift_KBF             NA
20  DRIFT   1   2   NA                     0
21  DRIFT   1   3   NA                     1
22  DRIFT   1   4   NA                     0
23  DRIFT   1   5   NA                     0
24  DRIFT   1   6   NA                     0
25  DRIFT   2   1   NA                     0
26  DRIFT   2   2   drift_MVT             NA
27  DRIFT   2   3   NA                     0
28  DRIFT   2   4   NA                     1
29  DRIFT   2   5   NA                     0
30  DRIFT   2   6   NA                     0
... ...     ... ... ...                   ...
109 T0VAR   2   1   T0var_MVT_KBF         NA
110 T0VAR   2   2   T0var_MVT             NA
111 T0VAR   2   3   NA                     0
112 T0VAR   2   4   NA                     0
113 T0VAR   2   5   NA                     0
114 T0VAR   2   6   NA                     0
115 T0VAR   3   1   T0var_cintKBF_KBF     NA
116 T0VAR   3   2   T0var_cintKBF_MVT     NA
117 T0VAR   3   3   T0var_cintKBF         NA
118 T0VAR   3   4   NA                     0
119 T0VAR   3   5   NA                     0
120 T0VAR   3   6   NA                     0
121 T0VAR   4   1   T0var_cintMVT_KBF     NA
122 T0VAR   4   2   T0var_cintMVT_MVT     NA
123 T0VAR   4   3   T0var_cintMVT_cintKBF NA
124 T0VAR   4   4   T0var_cintMVT         NA
125 T0VAR   4   5   NA                     0
126 T0VAR   4   6   NA                     0
127 T0VAR   5   1   NA                     0
128 T0VAR   5   2   NA                     0
129 T0VAR   5   3   NA                     0
130 T0VAR   5   4   NA                     0
131 T0VAR   5   5   NA                     0
132 T0VAR   5   6   NA                     0
133 T0VAR   6   1   NA                     0
134 T0VAR   6   2   NA                     0
135 T0VAR   6   3   NA                     0
136 T0VAR   6   4   NA                     0
137 T0VAR   6   5   NA                     0
138 T0VAR   6   6   NA                     0
    transform                              indvarying sdscale Is_exp2_effect
1   10 * param                              TRUE       1      FALSE
2   10 * param                              TRUE       1      FALSE
3   10 * param                              TRUE       1      FALSE
4   10 * param                              TRUE       1      FALSE
5   NA                                      TRUE      NA      FALSE
6   NA                                      TRUE      NA      FALSE
7   NA                                     FALSE      NA      FALSE
8   NA                                     FALSE      NA      FALSE
9   NA                                     FALSE      NA      FALSE
10  NA                                     FALSE      NA      FALSE
11  NA                                     FALSE      NA      FALSE
12  NA                                     FALSE      NA      FALSE
13  NA                                     FALSE      NA      FALSE
14  NA                                     FALSE      NA      FALSE
15  NA                                     FALSE      NA      FALSE
16  NA                                     FALSE      NA      FALSE
17  NA                                     FALSE      NA      FALSE
18  NA                                     FALSE      NA      FALSE
19  -(1e-06 + 2 * log1p_exp(-(2 * param))) FALSE       1      FALSE
20  NA                                     FALSE      NA      FALSE
21  NA                                     FALSE      NA      FALSE
22  NA                                     FALSE      NA      FALSE
23  NA                                     FALSE      NA      FALSE
24  NA                                     FALSE      NA      FALSE
25  NA                                     FALSE      NA      FALSE
26  -(1e-06 + 2 * log1p_exp(-(2 * param))) FALSE       1      FALSE
27  NA                                     FALSE      NA      FALSE
28  NA                                     FALSE      NA      FALSE
29  NA                                     FALSE      NA      FALSE
30  NA                                     FALSE      NA      FALSE
... ...                                    ...        ...     ...
109 2/(1 + exp(-param)) - 1                FALSE       1      FALSE
110 1e-10 + 5 * log1p_exp(2 * param)       FALSE       1      FALSE
111 NA                                     FALSE      NA      FALSE
112 NA                                     FALSE      NA      FALSE
113 NA                                     FALSE      NA      FALSE
114 NA                                     FALSE      NA      FALSE
115 2/(1 + exp(-param)) - 1                FALSE       1      FALSE
116 2/(1 + exp(-param)) - 1                FALSE       1      FALSE
117 1e-10 + 5 * log1p_exp(2 * param)       FALSE       1      FALSE
118 NA                                     FALSE      NA      FALSE
119 NA                                     FALSE      NA      FALSE
120 NA                                     FALSE      NA      FALSE
121 2/(1 + exp(-param)) - 1                FALSE       1      FALSE
122 2/(1 + exp(-param)) - 1                FALSE       1      FALSE
123 2/(1 + exp(-param)) - 1                FALSE       1      FALSE
124 1e-10 + 5 * log1p_exp(2 * param)       FALSE       1      FALSE
125 NA                                     FALSE      NA      FALSE
126 NA                                     FALSE      NA      FALSE
127 NA                                     FALSE      NA      FALSE
128 NA                                     FALSE      NA      FALSE
129 NA                                     FALSE      NA      FALSE
130 NA                                     FALSE      NA      FALSE
131 NA                                     FALSE      NA      FALSE
132 NA                                     FALSE      NA      FALSE
133 NA                                     FALSE      NA      FALSE
134 NA                                     FALSE      NA      FALSE
135 NA                                     FALSE      NA      FALSE
136 NA                                     FALSE      NA      FALSE
137 NA                                     FALSE      NA      FALSE
138 NA                                     FALSE      NA      FALSE
    Is_exp3_effect IsOFH_effect
1   FALSE          FALSE
2   FALSE          FALSE
3   FALSE          FALSE
4   FALSE          FALSE
5   FALSE          FALSE
6   FALSE          FALSE
7   FALSE          FALSE
8   FALSE          FALSE
9   FALSE          FALSE
10  FALSE          FALSE
11  FALSE          FALSE
12  FALSE          FALSE
13  FALSE          FALSE
14  FALSE          FALSE
15  FALSE          FALSE
16  FALSE          FALSE
17  FALSE          FALSE
18  FALSE          FALSE
19  FALSE          FALSE
20  FALSE          FALSE
21  FALSE          FALSE
22  FALSE          FALSE
23  FALSE          FALSE
24  FALSE          FALSE
25  FALSE          FALSE
26  FALSE          FALSE
27  FALSE          FALSE
28  FALSE          FALSE
29  FALSE          FALSE
30  FALSE          FALSE
... ...            ...
109 FALSE          FALSE
110 FALSE          FALSE
111 FALSE          FALSE
112 FALSE          FALSE
113 FALSE          FALSE
114 FALSE          FALSE
115 FALSE          FALSE
116 FALSE          FALSE
117 FALSE          FALSE
118 FALSE          FALSE
119 FALSE          FALSE
120 FALSE          FALSE
121 FALSE          FALSE
122 FALSE          FALSE
123 FALSE          FALSE
124 FALSE          FALSE
125 FALSE          FALSE
126 FALSE          FALSE
127 FALSE          FALSE
128 FALSE          FALSE
129 FALSE          FALSE
130 FALSE          FALSE
131 FALSE          FALSE
132 FALSE          FALSE
133 FALSE          FALSE
134 FALSE          FALSE
135 FALSE          FALSE
136 FALSE          FALSE
137 FALSE          FALSE
138 FALSE          FALSE

In [12]:
#group can vary in trend
model_fit$pars$Is_exp3_effect[model_fit$pars$matrix %in% c('T0MEANS','CINT')] = TRUE
model_fit$pars$Is_exp2_effect[model_fit$pars$matrix %in% c('T0MEANS','CINT')] = TRUE
model_fit$pars$IsOFH_effect[model_fit$pars$matrix %in% c('T0MEANS','CINT')] = TRUE
#model_fit$pars$Is_exp3_effect[(model_fit$pars$matrix %in% c('CINT','T0MEANS'))&(model_fit$pars$row %in% c(1,3))] = TRUE
#check what we did
model_fit$pars[model_fit$pars$matrix %in% c('T0MEANS','CINT'),]

    matrix  row col param       value transform  indvarying sdscale
1   T0MEANS 1   1   T0m_KBF     NA    10 * param TRUE        1
2   T0MEANS 2   1   T0m_MVT     NA    10 * param TRUE        1
3   T0MEANS 3   1   T0m_cintKBF NA    10 * param TRUE        1
4   T0MEANS 4   1   T0m_cintMVT NA    10 * param TRUE        1
5   T0MEANS 5   1   NA           0    NA         TRUE       NA
6   T0MEANS 6   1   NA           0    NA         TRUE       NA
97  CINT    1   1   NA           0    NA         TRUE       NA
98  CINT    2   1   NA           0    NA         TRUE       NA
99  CINT    3   1   NA           0    NA         TRUE       NA
100 CINT    4   1   NA           0    NA         TRUE       NA
101 CINT    5   1   NA           0    NA         TRUE       NA
102 CINT    6   1   NA           0    NA         TRUE       NA
    Is_exp2_effect Is_exp3_effect IsOFH_effect
1   TRUE           TRUE           TRUE
2   TRUE           TRUE           TRUE
3   TRUE           TRUE           TRUE
4   TRUE           TRUE           TRUE
5   TRUE           TRUE           TRUE
6   TRUE           TRUE           TRUE
97  TRUE           TRUE           TRUE
98  TRUE           TRUE           TRUE
99  TRUE           TRUE           TRUE
100 TRUE           TRUE           TRUE
101 TRUE           TRUE           TRUE
102 TRUE           TRUE           TRUE

In [13]:
unique(model_fit$pars$matrix)

[1] "T0MEANS"       "LAMBDA"        "DRIFT"         "DIFFUSION"
[5] "MANIFESTVAR"   "MANIFESTMEANS" "CINT"          "T0VAR"

In [15]:
set.seed(0)
# if no warning then do: 
fit_mvtha = ctStanFit(datalong=data_mvtha, ctstanmodel=model_fit, verbose=0, cores=cores_, nopriors=FALSE, #maybe TRUE when optimize ML
                      iter=iter_, chains=chains_, optimize=bool_optimize)#, optimcontrol = list(nsubsets=1)#, derrind) #nlcontrol=list(maxtimestep=10)
#Individual variation in T0VAR parameters not possible: as we have no variation at T0
ctsem:::ctSummarise(fit_mvtha, folder=file.path(path_save_,name), cores=cores_, ctStanPlotPost=F, nsamples=1000)
#"diag(.) had 0 or NA entries; non-finite result is doubtful": TODO: var in diffusiocov are set to 0... so maybe its normal?

Maximum a posteriori estimation requested

Setting DRIFT diagonals of 0 to approximate 0 of -1e-06

Free T0VAR parameters as well as indvarying T0MEANS -- fixing T0VAR pars to diag matrix of 1e-3

Uncentered TI predictors noted -- interpretability may be hindered and default priors may not be appropriate

Using 5/12 logical CPU cores

Doing 1st pass optimize...

Converged -- lp and par change within tolerances

Including TI predictors...

Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 28, 30, 31, 33, 34, 36, 37 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 28, 30, 31, 33, 34, 36, 37 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 28, 30, 31, 33, 34, 36, 37 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 28, 30, 31, 33, 34, 36, 37 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 28, 30, 31, 33, 34, 36, 37 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 28, 30, 31, 33, 34, 36, 37 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 28, 30, 31, 33, 34, 36, 37 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 28, 30, 31, 33, 34, 36, 37 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 28, 30, 31, 33, 34, 36, 37 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 28, 30, 31, 33, 34, 36, 37 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 28, 30, 31, 33, 34, 36, 37 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 28, 30, 31, 33, 34, 36, 37 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 28, 30, 31, 33, 34, 36, 37 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 28, 30, 31, 33, 34, 36, 37 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 28, 30, 31, 33, 34, 36, 37 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 28, 30, 31, 33, 34, 36, 37 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 28, 30, 31, 33, 34, 36, 37 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 28, 30, 31, 33, 34, 36, 37 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 30, 33, 36 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 30, 33, 36 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 30, 33, 36 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 30, 33, 36 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 30, 33, 36 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 30, 33, 36 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 30, 33, 36 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 30, 33, 36 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 30, 33, 36 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 30, 33, 36 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 30, 33, 36 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 30, 33, 36 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 30, 33, 36 is exactly zero, maybe model problem?"
Warning message in sgd(init, fitfunc = target, parsets = parsets, nsubsets = nsubsets, :
"Gradient of parameter 27, 30, 33, 36 is exactly zero, maybe model problem?"
Converged -- lp and par change within tolerances

Optimizing...

Converged -- lp change within itertol

Finishing optimization...

Estimating Hessian

Computing posterior with 1000 samples

Warning message in dir.create(file.path(oldwd, folder)):
"'G:\VPHI\Welfare\2- Research Projects\Camille Montalcini\Origins.GS\DataOutput\TrackingSystem\EXP2_\LongformatModels\PropZ5_severity_trend_rs0_\PropZ5_severity_trend_rs0_' existe déjà"
Computing quantities for 2000 samples...

Generating data from posterior mean

Using 5/12 logical CPU cores

Warning message in cov2cor(cp$T0cov):
"diag(.) had 0 or NA entries; non-finite result is doubtful"
Warning message in cov2cor(cp$DIFFUSIONcov):
"diag(.) had 0 or NA entries; non-finite result is doubtful"
Warning message in cov2cor(cp$asymDIFFUSION):
"diag(.) had 0 or NA entries; non-finite result is doubtful"
Computing quantities for 1 samples...

Free T0VAR parameters as well as indvarying T0MEANS -- fixing T0VAR pars to diag matrix of 1e-3

Free T0VAR parameters as well as indvarying T0MEANS -- fixing T0VAR pars to diag matrix of 1e-3

Computing quantities for 1000 samples...

Warning message:
"Using alpha for a discrete variable is not advised."
Warning message in ctKalman(fit = sf, subjects = 1:sf$standata$nsubjects, realid = TRUE, :
"Specified subjects not found in original id set -- assuming integers correspond to internal integer mapping. Consider setting realid=FALSE"
Computing state estimates..

Computing quantities for 1 samples...

Scale for colour is already present.
Adding another scale for colour, which will replace the existing scale.
Warning message in ctKalman(fit = sf, subjects = 1:sf$standata$nsubjects, realid = TRUE, :
"Specified subjects not found in original id set -- assuming integers correspond to internal integer mapping. Consider setting realid=FALSE"
Computing state estimates..

Computing quantities for 1 samples...

Scale for colour is already present.
Adding another scale for colour, which will replace the existing scale.
Warning message in ctKalman(fit = sf, subjects = 1:sf$standata$nsubjects, realid = TRUE, :
"Specified subjects not found in original id set -- assuming integers correspond to internal integer mapping. Consider setting realid=FALSE"

Computing state estimates..

Computing quantities for 1 samples...

Scale for colour is already present.
Adding another scale for colour, which will replace the existing scale.
Warning message in ctKalman(fit = sf, subjects = 1:sf$standata$nsubjects, realid = TRUE, :
"Specified subjects not found in original id set -- assuming integers correspond to internal integer mapping. Consider setting realid=FALSE"
Computing state estimates..

Computing quantities for 1 samples...

Scale for colour is already present.
Adding another scale for colour, which will replace the existing scale.
Warning message in ctKalman(fit = sf, subjects = 1:sf$standata$nsubjects, realid = TRUE, :
"Specified subjects not found in original id set -- assuming integers correspond to internal integer mapping. Consider setting realid=FALSE"
Computing state estimates..

Computing quantities for 1 samples...

Scale for colour is already present.
Adding another scale for colour, which will replace the existing scale.
Warning message in ctKalman(fit = sf, subjects = 1:sf$standata$nsubjects, realid = TRUE, :
"Specified subjects not found in original id set -- assuming integers correspond to internal integer mapping. Consider setting realid=FALSE"
Computing state estimates..

Computing quantities for 1 samples...

Scale for colour is already present.
Adding another scale for colour, which will replace the existing scale.
Warning message in ctKalman(fit = sf, subjects = 1:sf$standata$nsubjects, realid = TRUE, :
"Specified subjects not found in original id set -- assuming integers correspond to internal integer mapping. Consider setting realid=FALSE"
Computing state estimates..

Computing quantities for 1 samples...

Scale for colour is already present.
Adding another scale for colour, which will replace the existing scale.
Warning message in ctKalman(fit = sf, subjects = 1:sf$standata$nsubjects, realid = TRUE, :
"Specified subjects not found in original id set -- assuming integers correspond to internal integer mapping. Consider setting realid=FALSE"
Computing state estimates..

Computing quantities for 1 samples...

Scale for colour is already present.
Adding another scale for colour, which will replace the existing scale.
Computing state estimates..

Computing quantities for 1 samples...

Computing state estimates..

Computing quantities for 1 samples...

Warning message:
"Removed 30900 rows containing missing values (`geom_point()`)."
Warning message:
"Removed 30900 rows containing missing values (`geom_point()`)."
Warning message:
"Removed 10300 rows containing missing values (`geom_point()`)."
Warning message:
"Removed 10300 rows containing missing values (`geom_point()`)."
Computing temporal regression coefficients for 100 samples, may take a moment...

Computing temporal regression coefficients for 100 samples, may take a moment...

Getting 200 samples by 20 subjects for 4000 total samples

Calculating time independent predictor effects...

Computing quantities for 4000 samples...

Getting 200 samples by 20 subjects for 4000 total samples

Calculating time independent predictor effects...

Computing quantities for 4000 samples...

Getting 200 samples by 20 subjects for 4000 total samples

Calculating time independent predictor effects...

Computing quantities for 4000 samples...